servers:
  web:
    hosts:
      - 44.203.11.167

env:
  clear:
    NODE_ENV: production
    SOLANA_CLUSTER: mainnet-beta
    API_URL: https://api-main-mainnet.dreader.io
    D_READER_URL: https://dreader.app
    D_PUBLISHER_URL: https://dpublisher.app
    CDN_URL: 