global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9090

  - job_name: grafana
    static_configs:
      - targets:
          - grafana.dreader.io

  - job_name: loki
    static_configs:
      - targets:
          - loki.dreader.io

  - job_name: traefik
    static_configs:
      - targets:
          - 54.91.186.17:8080 # dev-devnet
          - 174.129.59.220:8080 # dev-mainnet
          - 3.239.214.202:8080 # main-devnet
          - 44.203.11.167:8080 # main-mainnet
          - 18.208.225.125:8080 # monitoring

  - job_name: node
    static_configs:
      - targets:
          - 54.91.186.17:9100 # dev-devnet
          - 174.129.59.220:9100 # dev-mainnet
          - 3.239.214.202:9100 # main-devnet
          - 44.203.11.167:9100 # main-mainnet
          - 18.208.225.125:9100 # monitoring
